Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Category.cs
using Bigon.WebUI.Models.Entities.Commons;

namespace Bigon.WebUI.Models.Entities
{
    public class Category :BaseEntity<int>
    {
        public string Name { get; set; }
        public int? ParentId { get; set; }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Color.cs
using Bigon.WebUI.Models.Entities.Commons;

namespace Bigon.WebUI.Models.Entities
{
    public class Color : BaseEntity<int>
    {

        public string Name { get; set; }
        public string HexCode { get; set; }
 
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Commons/AuditableEntity.cs
namespace Bigon.WebUI.Models.Entities.Commons
{
    public abstract class AuditableEntity
    {
        public int CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public int? LastModifiedBy { get; set; }
        public DateTime? LastModifiedAt { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DeletedAt { get; set; }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Commons/BaseEntity.cs
namespace Bigon.WebUI.Models.Entities.Commons
{
    public abstract class BaseEntity<TKey> : AuditableEntity
        where TKey : struct
    {
        public TKey Id { get; set; }

    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Material.cs
using Bigon.WebUI.Models.Entities.Commons;

namespace Bigon.WebUI.Models.Entities
{
    public class Material : BaseEntity<int>
    {
        public string Name { get; set; }

    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Entities/Size.cs
using Bigon.WebUI.Models.Entities.Commons;

namespace Bigon.WebUI.Models.Entities
{
    public class Size : BaseEntity<int>
    {

        public string Name { get; set; }
        public string ShortName { get; set; }

    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/Configurations/CategoryEntityConfiguration.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Bigon.WebUI.Models.Entities;

namespace Bigon.WebUI.Models.Persistences.Configurations
{
    public class CategoryEntityConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> builder)
        {
            builder.Property(m => m.Id).UseIdentityColumn(1, 1);
            builder.Property(m => m.ParentId).HasColumnType("int");
            builder.Property(m => m.Name).HasColumnType("nvarchar").HasMaxLength(200).IsRequired();
            builder.ConfigureAsAuditable();

            builder.HasOne<Category>()
                .WithMany()
                .HasForeignKey(m => m.ParentId)
                .HasPrincipalKey(m => m.Id);

            builder.HasKey(m => m.Id);
            builder.ToTable("Categories");
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/Configurations/ColorEntityConfiguration.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using Bigon.WebUI.Models.Entities;

namespace Bigon.WebUI.Models.Persistences.Configurations
{
    public class ColorEntityConfiguration : IEntityTypeConfiguration<Color>
    {
        public void Configure(EntityTypeBuilder<Color> builder)
        {
            builder.Property(m => m.Id).UseIdentityColumn(1, 1);
            builder.Property(m => m.Name).HasColumnType("nvarchar").HasMaxLength(200).IsRequired();
            builder.Property(m => m.HexCode).HasColumnType("varchar").HasMaxLength(7).IsRequired();
            builder.ConfigureAsAuditable();

            builder.HasKey(m => m.Id);
            builder.ToTable("Colors");
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/Configurations/ConfigurationHelper.cs
using Bigon.WebUI.Models.Entities.Commons;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bigon.WebUI.Models.Persistences.Configurations
{
    public static class ConfigurationHelper
    {
        public static EntityTypeBuilder<T> ConfigureAsAuditable<T>(this EntityTypeBuilder<T> builder)
            where T: AuditableEntity
        {
            builder.Property(m => m.CreatedBy).HasColumnType("int").IsRequired();
            builder.Property(m => m.CreatedAt).HasColumnType("datetime").IsRequired();
            builder.Property(m => m.LastModifiedBy).HasColumnType("int");
            builder.Property(m => m.LastModifiedAt).HasColumnType("datetime");
            builder.Property(m => m.DeletedBy).HasColumnType("int");
            builder.Property(m => m.DeletedAt).HasColumnType("datetime");

            return builder;
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/Configurations/MaterialEntityConfiguration.cs
using Bigon.WebUI.Models.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;

namespace Bigon.WebUI.Models.Persistences.Configurations
{
    public class MaterialEntityConfiguration : IEntityTypeConfiguration<Material>
    {
        public void Configure(EntityTypeBuilder<Material> builder)
        {
            builder.Property(m => m.Id).UseIdentityColumn(1, 1);
            builder.Property(m => m.Name).HasColumnType("nvarchar").HasMaxLength(200).IsRequired();
            builder.ConfigureAsAuditable();


            builder.HasKey(m => m.Id);
            builder.ToTable("Materials");
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/Configurations/SizeEntityConfiguration.cs
using Bigon.WebUI.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bigon.WebUI.Models.Persistences.Configurations
{
    public class SizeEntityConfiguration : IEntityTypeConfiguration<Size>
    {
        public void Configure(EntityTypeBuilder<Size> builder)
        {
            builder.Property(m => m.Id).UseIdentityColumn(1,1);
            builder.Property(m => m.Name).HasColumnType("nvarchar").HasMaxLength(200).IsRequired();
            builder.Property(m => m.ShortName).HasColumnType("varchar").HasMaxLength(5).IsRequired();
            builder.ConfigureAsAuditable();

            builder.HasKey(m => m.Id);
            builder.ToTable("Sizes");
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Models/Persistences/DataContext.cs
using Microsoft.EntityFrameworkCore;

namespace Bigon.WebUI.Models.Persistences
{
    public class DataContext : DbContext

    {
        public DataContext(DbContextOptions options)
            : base(options)
        {
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(DataContext).Assembly);
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class BlogsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            return View();
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Subscribe(string email)
        {
            return Json(new
            {
                error=false,
                email
            });
        }   

        public IActionResult SubscribeApprove()
        {
            return Content("Abone oldunuz");
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace Bigon.WebUI.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            return View();
        }
    }
}

Bigon-commerce-backend/Bigon.WebUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div id="shopify-section-template--14146645819443__main" class="shopify-section">
<!-- About Main Area Start -->
<div class="about-main-area" id="section-template--14146645819443__main">
  <div class="container">
    <div class="row">
      
      <div class="col-md-7 col-sm-6">
        <div class="about-img">
          <a href="about.html"><img class="img" src="../../cdn.shopify.com/s/files/1/0019/7181/4451/files/14056d.jpg?v=1523773888" alt="about-us"></a>
        </div>
      </div>
      
      
      <div class="col-md-5 col-sm-6">
        <div class="about-content">
          <h3>Why We are?</h3>
          <p>Mellentesque faucibus dapibus dapibus. Morbi aliquam aliquet neque. Donec placerat dapibus sollicitudin. Morbi arcu nisi, mattis ut ullamcorper in, dapibus ac nunc. Cras bibendum mauris et sapien feugiat. scelerisque accumsan nibh gravida. Quisque aliquet justo elementum lectus ultrices bibendum.
<br>
Mellentesque faucibus dapibus dapibus. Morbi aliquam aliquet neque. Donec placerat dapibus sollicitudin. Morbi arcu nisi, mattis ut ullamcorper in, dapibus ac nunc. Cras bibendum mauris et sapien feugiat. scelerisque accumsan nibh gravida. Quisque aliquet justo elementum lectus ultrices bibendum.
<br>
Mellentesque faucibus dapibus dapibus. Morbi aliquam aliquet neque. Donec placerat dapibus sollicitudin. Morbi arcu nisi, mattis ut ullamcorper in, dapibus ac nunc. Cras bibendum mauris et sapien feugiat. scelerisque accumsan nibh gravida. Quisque aliquet justo elementum lectus ultrices bibendum.</p>
          <ul class="mt-20 about-content-list">
            
            
          </ul>
        </div>
      </div>
      
    </div>
  </div>
</div>
<!-- About Main Area End -->

<style data-shopify>#section-template--14146645819443__main{padding-top: 0px;
    padding-bottom: 50px;}
  @@media (min-width: 768px) and (max-width: 991px) {
    #section-template--14146645819443__main{padding-top: 0px;
      padding-bottom: 50px;}
  }
  @@media (max-width: 767px) {
    #section-template--14146645819443__main{padding-top: 0px;
      padding-bottom: 50px;}
  }</style><style>


</style> 








</div><div id="shopify-section-template--14146645819443__about-bottom" class="shopify-section">
<!-- Our Mission Start -->
<div class="about-bottom" id="section-template--14146645819443__about-bottom">
  <div class="container">
    <div class="row">
      
      <div class="col-md-4 col-sm-12">
        <div class="ht-single-about">
          <h3>OUR SKILLS</h3>
          <div class="skill-bar">
            <div class="skill-bar-item">
              <span>WEB DESIGN</span>
              <div class="progress">
                <div class="progress-bar wow fadeInLeft" data-progress="80%" style="width: 80%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-wow-duration="1.5s" data-wow-delay="1.2s">
                  <span class="text-top">80%</span>
                </div>
              </div>
            </div>
            <div class="skill-bar-item">
              <span>PHP &amp; JAVASCRIPT</span>
              <div class="progress">
                <div class="progress-bar wow fadeInLeft" data-progress="90%" style="width: 90%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-wow-duration="1.5s" data-wow-delay="1.2s">
                  <span class="text-top">90%</span>
                </div>
              </div>
            </div>
            <div class="skill-bar-item">
              <span>HTML5 &amp; CSS3</span>
              <div class="progress">
                <div class="progress-bar wow fadeInLeft" data-progress="70%" style="width: 70%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-wow-duration="1.5s" data-wow-delay="1.2s">
                  <span class="text-top">70%</span>
                </div>
              </div>
            </div>
            <div class="skill-bar-item">
              <span>wordpress</span>
              <div class="progress">
                <div class="progress-bar wow fadeInLeft" data-progress="95%" style="width: 95%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-wow-duration="1.5s" data-wow-delay="1.2s">
                  <span class="text-top">95%</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
      <div class="col-md-4 col-sm-6">
        <div class="ht-single-about">
          <h3>OUR EXPERIENCES</h3>
          <h5>FUSCE FRINGILLA PORTTITOR IACULI SED QUAM LIBERO, ADIPISCING SED ERAT ID</h5>
          <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu nisi ac mi malesuada vestibulum. Phasellus tempor nunc eleifend cursus molestie. Mauris lectus arcu, pellentesque at sodales sit amet,</p>
        </div>
      </div>
      
      
      <div class="col-md-4 col-sm-6">
        <div class="ht-single-about">
          <h3>OUR WORKS</h3>
          <div class="ht-about-work">
            <span>1</span>
            <div class="ht-work-text">
              <h5><a href="#">LOREM IPSUM DOLOR SIT AMET</a></h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu nisi ac mi</p>
            </div>
          </div>
          <div class="ht-about-work">
            <span>2</span>
            <div class="ht-work-text">
              <h5><a href="#">DONEC FERMENTUM EROS</a></h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu nisi ac mi</p>
            </div>
          </div>
          <div class="ht-about-work">
            <span>3</span>
            <div class="ht-work-text">
              <h5><a href="#">LOREM IPSUM DOLOR SIT AMET</a></h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu nisi ac mi</p>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>
<!-- Our Mission End -->

<style data-shopify>#section-template--14146645819443__about-bottom{padding-top: 0px;
    padding-bottom: 50px;}
  @@media (min-width: 768px) and (max-width: 991px) {
    #section-template--14146645819443__about-bottom{padding-top: 0px;
      padding-bottom: 50px;}
  }
  @@media (max-width: 767px) {
    #section-template--14146645819443__about-bottom{padding-top: 0px;
      padding-bottom: 45px;}
  }</style><style>

</style> 







</div>

@section breadcrumbs{
    <div class="breadcrumbs-section ptb-50">
        <div class="breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="breadcrumbs-inner">

                            <nav class="" role="navigation" aria-label="breadcrumbs">
                                <ul class="breadcrumb-list">
                                    <li>
                                        <a asp-controller="home" asp-action="index" title="Back to the home page">Home</a>
                                    </li>
                                    <li>

                                        <span>about</span>

                                    </li>
                                </ul>
                            </nav>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Bigon-commerce-backend/Bigon.WebUI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div id="shopify-section-template--14146668527667__main" class="shopify-section">
<!-- Google Map Start -->
<div class="contact-map" id="section-template--14146668527667__main">
  <div class="container">
    <div id="map" style="height:400px"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDAq7MrCR1A2qIShmjbtLHSKjcEIEBEEwM"></script>
<script>
        // When the window has finished loading create our google map below
        google.maps.event.addDomListener(window, 'load', init);

        function init() {
            // Basic options for a simple Google Map
            // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
            var mapOptions = {
                // How zoomed in you want the map to start at (always required)
                zoom: 11,

                scrollwheel: false,

                // The latitude and longitude to center the map (always required)
                center: new google.maps.LatLng(23.761226, 90.420766), // New York

                // How you would like to style the map. 
                // This is where you would paste any style found on Snazzy Maps.
                styles: [{
                        "featureType": "administrative",
                        "elementType": "labels.text.fill",
                        "stylers": [{
                            "color": "#444444"
                        }]
                    },
                    {
                        "featureType": "landscape",
                        "elementType": "all",
                        "stylers": [{
                            "color": "#f2f2f2"
                        }]
                    },
                    {
                        "featureType": "poi",
                        "elementType": "all",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    },
                    {
                        "featureType": "road",
                        "elementType": "all",
                        "stylers": [{
                                "saturation": -100
                            },
                            {
                                "lightness": 45
                            }
                        ]
                    },
                    {
                        "featureType": "road.highway",
                        "elementType": "all",
                        "stylers": [{
                            "visibility": "simplified"
                        }]
                    },
                    {
                        "featureType": "road.arterial",
                        "elementType": "labels.icon",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    },
                    {
                        "featureType": "transit",
                        "elementType": "all",
                        "stylers": [{
                            "visibility": "off"
                        }]
                    },
                    {
                        "featureType": "water",
                        "elementType": "all",
                        "stylers": [{
                                "color": "#314453"
                            },
                            {
                                "visibility": "on"
                            }
                        ]
                    },
                    {
                        "featureType": "water",
                        "elementType": "geometry.fill",
                        "stylers": [{
                                "lightness": "-12"
                            },
                            {
                                "saturation": "0"
                            },
                            {
                                "color": "#4bc7e9"
                            }
                        ]
                    }
                ]
            };

            // Get the HTML DOM element that will contain your map 
            // We are using a div with id="map" seen below in the <body>
            var mapElement = document.getElementById('map');

            // Create the Google Map using our element and options defined above
            var map = new google.maps.Map(mapElement, mapOptions);

            // Let's also add a marker while we're at it
            var marker = new google.maps.Marker({
                position: new google.maps.LatLng(23.761226, 90.420766),
                map: map,
                title: 'Snazzy!'
            });
        }
</script>
  </div>
</div>

<style data-shopify>#section-template--14146668527667__main{padding-top: 0px;
    padding-bottom: 50px;}
  @@media (min-width: 768px) and (max-width: 991px) {
    #section-template--14146668527667__main{padding-top: 0px;
      padding-bottom: 50px;}
  }
  @@media (max-width: 767px) {
    #section-template--14146668527667__main{padding-top: 0px;
      padding-bottom: 50px;}
  }</style>




</div><div id="shopify-section-template--14146668527667__contact-form" class="shopify-section">
<!-- Google Map End -->
<!-- Contact Email Area Start -->
<div class="contact-email-area" id="section-template--14146668527667__contact-form">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h3 class="mb-5">Contact Us</h3>
        <p class="text-capitalize mb-40">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        <form method="post" action="https://bigon-5.myshopify.com/contact#contact_form" id="contact_form" accept-charset="UTF-8" class="contact-form"><input type="hidden" name="form_type" value="contact" /><input type="hidden" name="utf8" value="✓" />
        
        
        <div class="address-wrapper row">
          <div class="col-md-6">
            <div class="address-fname">
              <input type="text"  name="contact[name]" id="contactFormName" value=""  placeholder="">
            </div>
          </div>
          <div class="col-md-6">
            <div class="address-email">
              <input type="text" name="contact[email]" id="contactEmail" value="" placeholder="">
            </div>
          </div>
          <div class="col-xs-12">
            <div class="address-subject">
              <input type="text"  name="contact[subject]" id="contactSubject" value="" placeholder="">
            </div>
          </div>
          <div class="col-xs-12">
            <div class="address-textarea">
              <textarea name="contact[body]"  placeholder=""></textarea>
            </div>
          </div>
        </div>
        <p class="form-message ml-15"></p>
        <div class="col-xs-12 footer-content mail-content">
          <div class="send-email pull-right">
            <input type="submit" value="Submit" class="submit">
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- Contact Email Area End -->

<style data-shopify>#section-template--14146668527667__contact-form{padding-top: 0px;
    padding-bottom: 50px;}
  @@media (min-width: 768px) and (max-width: 991px) {
    #section-template--14146668527667__contact-form{padding-top: 0px;
      padding-bottom: 50px;}
  }
  @@media (max-width: 767px) {
    #section-template--14146668527667__contact-form{padding-top: 0px;
      padding-bottom: 45px;}
  }</style>




</div>

@section breadcrumbs{
    <div class="breadcrumbs-section ptb-50">
        <div class="breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="breadcrumbs-inner">

                            <nav class="" role="navigation" aria-label="breadcrumbs">
                                <ul class="breadcrumb-list">
                                    <li>
                                        <a asp-controller="home" asp-action="index" title="Back to the home page">Home</a>
                                    </li>
                                    <li>

                                        <span>contact</span>

                                    </li>
                                </ul>
                            </nav>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Bigon-commerce-backend/Bigon.WebUI/Views/Shared/_Navbar.cshtml
<nav>
    <ul class="middle-menu-list">

        <li>
            <a asp-controller="home" asp-action="index">Home</a>
        </li>

        <li>
            <a asp-controller="Shop" asp-action="index">shop</a>
        </li>

        <li>
            <a asp-controller="Blogs" asp-action="index">blog</a>
        </li>

        <li><a asp-controller="home" asp-action="about">about us</a></li>


        <li><a asp-controller="home" asp-action="contact">contact us</a></li>

    </ul>
</nav>